/*
 * CadastroPecas.java
 * 
 * Copyright © 2014 Rogério Eduardo Pereira <rogeriopereira.info@gmail.com>. 
 * 
 * This file is part of AssistenciaTecnica.
 * 
 * AssistenciaTecnica is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AssistenciaTecnica is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AssistenciaTecnica.  If not, see <http ://www.gnu.org/licenses/>.
 */

package assistenciatecnica.view;

import assistenciatecnica.control.ControladorBancodeDados;
import assistenciatecnica.control.ControladorFornecedores;
import assistenciatecnica.control.ControladorPeca;
import assistenciatecnica.control.util.ControladorTabelas;
import assistenciatecnica.model.Fornecedores;
import assistenciatecnica.model.Pecas;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rogério Eduardo Pereira
 * Data Criação: Jun 18, 2014
 */
public class CadastroPecas extends javax.swing.JFrame implements KeyListener, ContainerListener
{

    /** Creates new form CadastroPecas */
    public CadastroPecas() {
        initComponents();

        //Adiciona Listeners de Botões
        addKeyAndContainerListenerRecursively(this);

	this.setLocationRelativeTo(null);
	
	this.textoCodigo.setText("** NOVO **");	
	
	this.configuraTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        PainelAbas = new javax.swing.JTabbedPane();
        painelPeca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        textoPeca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoValor = new formattedFields.jTextMoeda();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        textoQuantidade = new javax.swing.JFormattedTextField();
        PainelFornecedores = new javax.swing.JPanel();
        botaoAdicionarFornecedor = new javax.swing.JButton();
        botaoRemoverFornecedore = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFornecedor = new javax.swing.JTable();
        botaoSalvar = new javax.swing.JButton();
        botaoProcurar = new javax.swing.JButton();
        botaoApagar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Peças");

        jLabel1.setText("Codigo");

        textoCodigo.setEditable(false);
        textoCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoCodigo.setForeground(java.awt.Color.red);
        textoCodigo.setFocusable(false);

        textoPeca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoPecaKeyTyped(evt);
            }
        });

        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Peça");

        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Valor");

        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Quantidade");

        jLabel5.setText("Observações");

        textoObs.setColumns(20);
        textoObs.setRows(5);
        textoObs.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoObsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textoObs);

        textoQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        textoQuantidade.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoQuantidadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout painelPecaLayout = new javax.swing.GroupLayout(painelPeca);
        painelPeca.setLayout(painelPecaLayout);
        painelPecaLayout.setHorizontalGroup(
            painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPecaLayout.createSequentialGroup()
                        .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(painelPecaLayout.createSequentialGroup()
                                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(10, 10, 10)
                                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(textoPeca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoQuantidade, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        painelPecaLayout.setVerticalGroup(
            painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelAbas.addTab("Peça", painelPeca);

        botaoAdicionarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-add.png"))); // NOI18N
        botaoAdicionarFornecedor.setText("Adicionar");
        botaoAdicionarFornecedor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoAdicionarFornecedorActionPerformed(evt);
            }
        });

        botaoRemoverFornecedore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-delete-2.png"))); // NOI18N
        botaoRemoverFornecedore.setText("Remover");
        botaoRemoverFornecedore.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoRemoverFornecedoreActionPerformed(evt);
            }
        });

        tabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Codigo", "Fornecedor"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tabelaFornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(tabelaFornecedor);

        javax.swing.GroupLayout PainelFornecedoresLayout = new javax.swing.GroupLayout(PainelFornecedores);
        PainelFornecedores.setLayout(PainelFornecedoresLayout);
        PainelFornecedoresLayout.setHorizontalGroup(
            PainelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(PainelFornecedoresLayout.createSequentialGroup()
                        .addComponent(botaoAdicionarFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(botaoRemoverFornecedore)))
                .addContainerGap())
        );
        PainelFornecedoresLayout.setVerticalGroup(
            PainelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemoverFornecedore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelAbas.addTab("Fornecedores", PainelFornecedores);

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/accept.png"))); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/magnifier.png"))); // NOI18N
        botaoProcurar.setText("Procurar");
        botaoProcurar.setMaximumSize(new java.awt.Dimension(81, 23));
        botaoProcurar.setMinimumSize(new java.awt.Dimension(81, 23));
        botaoProcurar.setPreferredSize(new java.awt.Dimension(81, 23));
        botaoProcurar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarActionPerformed(evt);
            }
        });

        botaoApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-delete-2.png"))); // NOI18N
        botaoApagar.setText("Apagar");
        botaoApagar.setEnabled(false);
        botaoApagar.setMaximumSize(new java.awt.Dimension(81, 23));
        botaoApagar.setMinimumSize(new java.awt.Dimension(81, 23));
        botaoApagar.setPreferredSize(new java.awt.Dimension(81, 23));
        botaoApagar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoApagarActionPerformed(evt);
            }
        });

        botaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/pencil.png"))); // NOI18N
        botaoAlterar.setText("Alterar");
        botaoAlterar.setEnabled(false);
        botaoAlterar.setMaximumSize(new java.awt.Dimension(81, 23));
        botaoAlterar.setMinimumSize(new java.awt.Dimension(81, 23));
        botaoAlterar.setPreferredSize(new java.awt.Dimension(81, 23));
        botaoAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelAbas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelAbas.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoPecaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoPecaKeyTyped
    {//GEN-HEADEREND:event_textoPecaKeyTyped
		int t = textoPeca.getText().length();
		if(t == 50)
		evt.setKeyChar((char) KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_textoPecaKeyTyped

    private void textoObsKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoObsKeyTyped
    {//GEN-HEADEREND:event_textoObsKeyTyped
		int t = textoObs.getText().length();
		if(t == 999999999)
		evt.setKeyChar((char) KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_textoObsKeyTyped

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoSalvarActionPerformed
    {//GEN-HEADEREND:event_botaoSalvarActionPerformed
		if(this.validaCampos())
		{
			controladorBD				= new ControladorBancodeDados();
			controlador				= new ControladorPeca();

			if(this.textoCodigo.getText().equals("** NOVO **"))
				this.peca = new Pecas();
			else
				this.peca = controlador.getPecaByCodigo(Long.parseLong(this.textoCodigo.getText()), this);

			//Seta os valores
			this.peca.setPeca(this.textoPeca.getText());
			this.peca.setValor(this.textoValor.getValue());
			this.peca.setQuantidade(Integer.parseInt(this.textoQuantidade.getText()));
			this.peca.setObservacao(this.textoObs.getText());
			
			//Fornecedores
			if(tabelaFornecedor.isEditing())
				tabelaFornecedor.getCellEditor().stopCellEditing();
			List<Fornecedores> fornecedores = new ArrayList<Fornecedores>();
			for(int i=0; i<tabelaFornecedor.getRowCount(); i++)
			{
				Fornecedores fornecedor	= new Fornecedores();
				fornecedor = new ControladorFornecedores().getFornecedorByCodigo(Long.parseLong(tabelaFornecedor.getValueAt(i, 0).toString()), this);
				
				fornecedores.add(fornecedor);
			}
			this.peca.setFornecedores(fornecedores);

			//Atualiza Banco
			if(this.textoCodigo.getText().equals("** NOVO **"))
				controladorBD.cadastrar(this.peca, (JFrame)this);
			else
				controladorBD.atualizar(this.peca, (JFrame)this);

			this.limpaTela();
			this.habilitaCampos(true);
			this.botaoAlterar.setEnabled(false);
			this.botaoApagar.setEnabled(false);

			controladorBD				= null;
			controlador				= null;
		}
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoProcurarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarActionPerformed
		ProcurarPecas j = new ProcurarPecas();
		j.setJanela(this);
		j.setVisible(true);
    }//GEN-LAST:event_botaoProcurarActionPerformed

    private void botaoApagarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoApagarActionPerformed
    {//GEN-HEADEREND:event_botaoApagarActionPerformed
		this.controladorBD		= new ControladorBancodeDados();
		this.controlador		= new ControladorPeca();

		Long		codigo		= Long.parseLong(this.textoCodigo.getText());

		//Apagando Local de evento
		this.controladorBD.apagar(codigo, this.peca, (JFrame)this);

		this.controladorBD		= null;
		this.controlador		= null;
		this.limpaTela();
		this.habilitaCampos(true);
    }//GEN-LAST:event_botaoApagarActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoAlterarActionPerformed
    {//GEN-HEADEREND:event_botaoAlterarActionPerformed
		this.habilitaCampos(true);
		botaoSalvar.setEnabled(true);
		botaoAlterar.setEnabled(false);
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void textoQuantidadeKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoQuantidadeKeyTyped
    {//GEN-HEADEREND:event_textoQuantidadeKeyTyped
		int tecla = evt.getKeyChar();
		if	(
				(tecla == 48) ||	//0
				(tecla == 49) ||	//1
				(tecla == 50) ||	//2
				(tecla == 51) ||	//3
				(tecla == 52) ||	//4
				(tecla == 53) ||	//5
				(tecla == 54) ||	//6
				(tecla == 55) ||	//7
				(tecla == 56) ||	//8
				(tecla == 57)		//9
			)
		{
			
		}
		else
			evt.setKeyChar((char) KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_textoQuantidadeKeyTyped

    private void botaoRemoverFornecedoreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoRemoverFornecedoreActionPerformed
    {//GEN-HEADEREND:event_botaoRemoverFornecedoreActionPerformed
		DefaultTableModel modelo = (DefaultTableModel) tabelaFornecedor.getModel();
		modelo.removeRow(tabelaFornecedor.getSelectedRow());
    }//GEN-LAST:event_botaoRemoverFornecedoreActionPerformed

    private void botaoAdicionarFornecedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoAdicionarFornecedorActionPerformed
    {//GEN-HEADEREND:event_botaoAdicionarFornecedorActionPerformed
		ProcuraFornecedores jpf = new ProcuraFornecedores(this, true);
		jpf.setVisible(true);
    }//GEN-LAST:event_botaoAdicionarFornecedorActionPerformed


    /*
     * Métodos da Classe
     */
    
    //METODOS KEYLISTENER
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  

    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {

        }

        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            this.Fechar();
        }
    }
    
    
    /*
     * Método Fechar()
     * Fecha Janela
     */
    private void Fechar()
    {
        this.dispose();
    }
	
	/*
	 * Método configuraTabela
	 * Configura o tamanho das tabelas
	 */
	private void configuraTabela()
	{
		DefaultTableCellRenderer alinhamento = new DefaultTableCellRenderer();
		alinhamento.setHorizontalAlignment(SwingConstants.LEFT);
		tabelaFornecedor.getColumnModel().getColumn(0).setCellRenderer(alinhamento);
		
		tabelaFornecedor.getColumnModel().getColumn(0).setPreferredWidth(60); 
		tabelaFornecedor.getColumnModel().getColumn(1).setPreferredWidth(165); 
	}
	
	/*
	 * Método validaCampos
	 * Valida os campos obrigatorios
	 */
	private Boolean validaCampos()
	{
		Boolean valida = true;
		
		if(textoPeca.getText().isEmpty())
			valida = false;
		if(textoValor.getValue().isNaN() || textoValor.getText().isEmpty()) 
			valida = false;
		if(textoQuantidade.getText().isEmpty())
			valida = false;
		
		if(valida == false)
			JOptionPane.showMessageDialog(this, "Campo em branco", "Erro", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("img/error-circle.png"));
			
		return valida;
		
	}
	
	/*
	 * Método habilitaCampos
	 * Habilita/Desabilita Campos
	 */
	private void habilitaCampos(Boolean habilita)
	{
		textoCodigo.setEnabled(habilita);
		textoPeca.setEnabled(habilita);
		textoValor.setEnabled(habilita);
		textoQuantidade.setEnabled(habilita);
		textoObs.setEnabled(habilita);
		
		botaoAdicionarFornecedor.setEnabled(habilita);
		botaoRemoverFornecedore.setEnabled(habilita);
		tabelaFornecedor.setEnabled(habilita);
	}
	
	/*
	 * Método limpaTela
	 * limpa os campos
	 */
	public void limpaTela()
	{
		textoCodigo.setText("");
		textoPeca.setText("");
		textoValor.setText(0.0);
		textoQuantidade.setText("");
		textoObs.setText("");
		
		new ControladorTabelas().apagaTabela(tabelaFornecedor);
	}
	
	/*
	 * Método adicionaFornecedor
	 * Adiciona o fornecedor na tabela
	 */
	public Boolean adicionaFornecedor(String codigo, String fornecedor)
	{
		try
		{
			Boolean insere = true;

			for(int i=0; i<tabelaFornecedor.getRowCount(); i++)
			{
				if(tabelaFornecedor.getValueAt(i, 0).toString().equals(codigo))
					insere = false;
			}

			if(insere)
			{
				DefaultTableModel modelo = (DefaultTableModel) tabelaFornecedor.getModel();
				modelo.addRow(new String[]	{
											codigo,
											fornecedor
										});
			}

			return true;
		}
		catch (Exception e)
		{
			return false;
		}
	}
	
	/*
	 * Método getServicoByCodigo
	 * Obtém o servico de acordo com o codigo
	 */
	public void getPecaByCodigo(Long codigo)
	{
		this.controlador	= new ControladorPeca();
		this.peca			= this.controlador.getPecaByCodigo(codigo, this);
		
		//Seta os valores
		this.textoCodigo.setText(this.peca.getCodigo().toString());
		this.textoPeca.setText(this.peca.getPeca());
		this.textoValor.setText(this.peca.getValor());
		this.textoQuantidade.setText(String.valueOf(this.peca.getQuantidade()));
		this.textoObs.setText(this.peca.getObservacao());
		
		for(Fornecedores fornecedor: this.peca.getFornecedores())
		{
			this.adicionaFornecedor(fornecedor.getCodigo().toString(), fornecedor.getNome());
		}
		
		this.habilitaCampos(false);
		
		botaoApagar.setEnabled(true);
		botaoAlterar.setEnabled(true);
	}
			


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPecas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PainelAbas;
    private javax.swing.JPanel PainelFornecedores;
    private javax.swing.JButton botaoAdicionarFornecedor;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoApagar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JButton botaoRemoverFornecedore;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelPeca;
    private javax.swing.JTable tabelaFornecedor;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextField textoPeca;
    private javax.swing.JFormattedTextField textoQuantidade;
    private formattedFields.jTextMoeda textoValor;
    // End of variables declaration//GEN-END:variables
	private	ControladorBancodeDados	controladorBD;
	private	ControladorPeca			controlador;
	private	Pecas					peca;
}
