/*
 * CadastroServicos.java
 * 
 * Copyright © 2014 Rogério Eduardo Pereira <rogeriopereira.info@gmail.com>. 
 * 
 * This file is part of AssistenciaTecnica.
 * 
 * AssistenciaTecnica is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AssistenciaTecnica is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AssistenciaTecnica.  If not, see <http ://www.gnu.org/licenses/>.
 */

package assistenciatecnica.view;

import assistenciatecnica.control.ControladorBancodeDados;
import assistenciatecnica.control.ControladorClientes;
import assistenciatecnica.control.ControladorServico;
import assistenciatecnica.model.Clientes;
import assistenciatecnica.model.Servicos;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rogério Eduardo Pereira
 * Data Criação: Jun 17, 2014
 */
public class CadastroServicos extends javax.swing.JFrame implements KeyListener, ContainerListener
{

    /** Creates new form CadastroServicos */
    public CadastroServicos() {
        initComponents();

        //Adiciona Listeners de Botões
        addKeyAndContainerListenerRecursively(this);

	this.setLocationRelativeTo(null);
	
	this.textoCodigo.setText("** NOVO **");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoServico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoValor = new formattedFields.jTextMoeda();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        botaoSalvar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoApagar = new javax.swing.JButton();
        botaoProcurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Serviços");

        jLabel1.setText("Codigo");

        textoCodigo.setEditable(false);
        textoCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textoCodigo.setForeground(java.awt.Color.red);
        textoCodigo.setFocusable(false);

        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("Serviço");

        textoServico.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoServicoKeyTyped(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Valor");

        jLabel4.setText("Observações");

        textoObs.setColumns(20);
        textoObs.setRows(5);
        textoObs.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                textoObsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textoObs);

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/accept.png"))); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/pencil.png"))); // NOI18N
        botaoAlterar.setText("Alterar");
        botaoAlterar.setEnabled(false);
        botaoAlterar.setMaximumSize(new java.awt.Dimension(81, 23));
        botaoAlterar.setMinimumSize(new java.awt.Dimension(81, 23));
        botaoAlterar.setPreferredSize(new java.awt.Dimension(81, 23));
        botaoAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-delete-2.png"))); // NOI18N
        botaoApagar.setText("Apagar");
        botaoApagar.setEnabled(false);
        botaoApagar.setMaximumSize(new java.awt.Dimension(81, 23));
        botaoApagar.setMinimumSize(new java.awt.Dimension(81, 23));
        botaoApagar.setPreferredSize(new java.awt.Dimension(81, 23));
        botaoApagar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoApagarActionPerformed(evt);
            }
        });

        botaoProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/magnifier.png"))); // NOI18N
        botaoProcurar.setText("Procurar");
        botaoProcurar.setMaximumSize(new java.awt.Dimension(81, 23));
        botaoProcurar.setMinimumSize(new java.awt.Dimension(81, 23));
        botaoProcurar.setPreferredSize(new java.awt.Dimension(81, 23));
        botaoProcurar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoCodigo)
                                    .addComponent(textoServico)
                                    .addComponent(textoValor, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoServicoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoServicoKeyTyped
    {//GEN-HEADEREND:event_textoServicoKeyTyped
		int t = textoServico.getText().length();
		if(t == 50)
			evt.setKeyChar((char) KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_textoServicoKeyTyped

    private void textoObsKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_textoObsKeyTyped
    {//GEN-HEADEREND:event_textoObsKeyTyped
		int t = textoObs.getText().length();
		if(t == 999999999)
			evt.setKeyChar((char) KeyEvent.VK_CLEAR);
    }//GEN-LAST:event_textoObsKeyTyped

    private void botaoProcurarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarActionPerformed
		ProcurarServico j = new ProcurarServico();
		j.setJanela(this);
		j.setVisible(true);
    }//GEN-LAST:event_botaoProcurarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoSalvarActionPerformed
    {//GEN-HEADEREND:event_botaoSalvarActionPerformed
		if(this.validaCampos())
		{
			controladorBD	= new ControladorBancodeDados();
			controlador	= new ControladorServico();

			if(this.textoCodigo.getText().equals("** NOVO **"))
				this.servico = new Servicos();
			else
				this.servico = controlador.getServicoByCodigo(Long.parseLong(this.textoCodigo.getText()), this);
			
			//Seta os valores
			this.servico.setServico(this.textoServico.getText());
			this.servico.setValor(this.textoValor.getValue());
			this.servico.setObservacao(this.textoObs.getText());
			
			//Atualiza Banco
			if(this.textoCodigo.getText().equals("** NOVO **"))
				controladorBD.cadastrar(this.servico, (JFrame)this);
			else
				controladorBD.atualizar(this.servico, (JFrame)this);

			this.limpaTela();
			this.habilitaCampos(true);
			this.botaoAlterar.setEnabled(false);
			this.botaoApagar.setEnabled(false);

			controladorBD	= null;
			controlador	= null;
		}
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoAlterarActionPerformed
    {//GEN-HEADEREND:event_botaoAlterarActionPerformed
		this.habilitaCampos(true);
		botaoSalvar.setEnabled(true);
		botaoAlterar.setEnabled(false);
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoApagarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoApagarActionPerformed
    {//GEN-HEADEREND:event_botaoApagarActionPerformed
		this.controladorBD		= new ControladorBancodeDados();
		this.controlador		= new ControladorServico();
		
		Long		codigo	= Long.parseLong(this.textoCodigo.getText());
		
		//Apagando Local de evento
		this.controladorBD.apagar(codigo, this.servico, (JFrame)this);
		
		this.controladorBD	= null;
		this.controlador	= null;
		this.limpaTela();
		this.habilitaCampos(true);
    }//GEN-LAST:event_botaoApagarActionPerformed


    /*
     * Métodos da Classe
     */
    
    //METODOS KEYLISTENER
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  

    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {
		this.botaoSalvar.doClick();
        }

        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            this.Fechar();
        }
    }
    
    
    /*
     * Método Fechar()
     * Fecha Janela
     */
    private void Fechar()
    {
        this.dispose();
    }
	
	/*
	 * Método Valida Campos
	 * Valida os campos obrigatorios
	 */
	private boolean validaCampos()
	{
		boolean valida = true;
		
		if(textoServico.getText().isEmpty())
			valida = false;
		if(textoValor.getValue().isNaN() || textoValor.getText().isEmpty()) 
			valida = false;
			
		if(valida == false)
			JOptionPane.showMessageDialog(this, "Campo em branco", "Erro", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("img/error-circle.png"));
		
		return valida;
	}
	
	/*
	 * Método limpaTela
	 * Limpa todos os campos
	 */
	public void limpaTela()
	{
		this.textoCodigo.setText("** NOVO **");
		this.textoServico.setText("");
		this.textoValor.setText(0.0);
		this.textoObs.setText("");
	}
	
	/*
	 * Método habilita campos
	 * Habilita/Desabilita campos
	 */
	private void habilitaCampos(Boolean habilita)
	{
		this.textoCodigo.setEnabled(habilita);
		this.textoServico.setEnabled(habilita);
		this.textoValor.setEnabled(habilita);
		this.textoObs.setEnabled(habilita);
	}
	
	/*
	 * Método getServicoByCodigo
	 * Obtém o servico de acordo com o codigo
	 */
	public void getServicoByCodigo(Long codigo)
	{
		this.controlador	= new ControladorServico();
		this.servico		= this.controlador.getServicoByCodigo(codigo, this);
		
		//Seta os valores
		this.textoCodigo.setText(this.servico.getCodigo().toString());
		this.textoServico.setText(this.servico.getServico());
		this.textoValor.setText(this.servico.getValor());
		this.textoObs.setText(this.servico.getObservacao());
		
		this.habilitaCampos(false);
		
		botaoApagar.setEnabled(true);
		botaoAlterar.setEnabled(true);
	}
	


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoApagar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextField textoServico;
    private formattedFields.jTextMoeda textoValor;
    // End of variables declaration//GEN-END:variables
	private	ControladorBancodeDados	controladorBD;
	private	ControladorServico			controlador;
	private	Servicos					servico;
}
