/*
 * OrdemDeServico.java
 * 
 * Copyright © 2014 Rogério Eduardo Pereira <rogeriopereira.info@gmail.com>. 
 * 
 * This file is part of AssistenciaTecnica.
 * 
 * AssistenciaTecnica is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AssistenciaTecnica is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AssistenciaTecnica.  If not, see <http ://www.gnu.org/licenses/>.
 */

package assistenciatecnica.view;

import assistenciatecnica.control.ControladorAtendimentos;
import assistenciatecnica.control.ControladorClientes;
import assistenciatecnica.model.Clientes;
import assistenciatecnica.model.OrdemServico;
import assistenciatecnica.model.Usuario;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;

/**
 *
 * @author Rogério Eduardo Pereira
 * Data Criação: Jun 20, 2014
 */
public class OrdemDeServico extends javax.swing.JFrame implements KeyListener, ContainerListener
{

    /** Creates new form OrdemDeServico */
    public OrdemDeServico() {
        initComponents();

        //Adiciona Listeners de Botões
        addKeyAndContainerListenerRecursively(this);

	this.setLocationRelativeTo(null);
	
	textoCodigo.setText("** NOVO **");
	textoStatus.setText("Abertura");
	
	this.getAtendimentos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        PainelCodigo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoStatus = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        botaoClienteAdicionar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textoCliente = new javax.swing.JTextField();
        botaoProcurarCliente = new javax.swing.JButton();
        botaoAdicionarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoDefeito = new javax.swing.JTextArea();
        textoTecnico = new javax.swing.JTextField();
        botaoProcurarTecnico = new javax.swing.JButton();
        botaoAdicionarTecnico = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textoEquipamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textoModelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoNumeroSerie = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        comboAtendimento = new javax.swing.JComboBox();
        painelPeças = new javax.swing.JPanel();
        botaoAdicionarPeca = new javax.swing.JButton();
        botaoRemoverPeca = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPecas = new javax.swing.JTable();
        painelServicos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaServicos = new javax.swing.JTable();
        botaoAdicionarServico = new javax.swing.JButton();
        botaoRemoverServico = new javax.swing.JButton();
        PainelPagamentos = new javax.swing.JPanel();
        botaoAdicionarPagamento = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaServicos1 = new javax.swing.JTable();
        botaoRemoverPagamento = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textoParcelas = new javax.swing.JTextField();
        painelObservacoes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoObservacoes = new javax.swing.JTextArea();
        PainelRecebimentos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TextoPorcentagemDesconto = new javax.swing.JTextField();
        textoDesconto = new formattedFields.jTextMoeda();
        textoTotal = new formattedFields.jTextMoeda();
        textoValorPago = new formattedFields.jTextMoeda();
        textoValorReceber = new formattedFields.jTextMoeda();
        botaoSalvar = new javax.swing.JButton();
        botaoProcurar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordem de Serviço");

        PainelCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(95, 133, 169), null), "Código", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Codigo");

        textoCodigo.setEditable(false);
        textoCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textoCodigo.setForeground(java.awt.Color.red);
        textoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoCodigo.setFocusable(false);

        jLabel2.setText("Status");

        textoStatus.setEditable(false);
        textoStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textoStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoStatus.setFocusable(false);

        javax.swing.GroupLayout PainelCodigoLayout = new javax.swing.GroupLayout(PainelCodigo);
        PainelCodigo.setLayout(PainelCodigoLayout);
        PainelCodigoLayout.setHorizontalGroup(
            PainelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PainelCodigoLayout.setVerticalGroup(
            PainelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Cliente");

        textoCliente.setEditable(false);
        textoCliente.setFocusable(false);

        botaoProcurarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-green_menor_buscar.png"))); // NOI18N
        botaoProcurarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarClienteActionPerformed(evt);
            }
        });

        botaoAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-green_menor_add.png"))); // NOI18N
        botaoAdicionarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoAdicionarClienteActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.red);
        jLabel4.setText("Técnico");

        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("Defeito");

        textoDefeito.setColumns(20);
        textoDefeito.setLineWrap(true);
        textoDefeito.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textoDefeito);

        textoTecnico.setEditable(false);
        textoTecnico.setFocusable(false);

        botaoProcurarTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-black_menor_buscar.png"))); // NOI18N
        botaoProcurarTecnico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarTecnicoActionPerformed(evt);
            }
        });

        botaoAdicionarTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-black_menor_add.png"))); // NOI18N
        botaoAdicionarTecnico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoAdicionarTecnicoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(java.awt.Color.red);
        jLabel5.setText("Equipamento");

        jLabel6.setText("Modelo");

        jLabel7.setText("Numero Série");

        jLabel15.setForeground(java.awt.Color.red);
        jLabel15.setText("Atendimento");

        javax.swing.GroupLayout botaoClienteAdicionarLayout = new javax.swing.GroupLayout(botaoClienteAdicionar);
        botaoClienteAdicionar.setLayout(botaoClienteAdicionarLayout);
        botaoClienteAdicionarLayout.setHorizontalGroup(
            botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoClienteAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(botaoClienteAdicionarLayout.createSequentialGroup()
                        .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addGap(10, 10, 10)
                        .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(botaoClienteAdicionarLayout.createSequentialGroup()
                                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCliente)
                                    .addComponent(textoTecnico))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(botaoClienteAdicionarLayout.createSequentialGroup()
                                        .addComponent(botaoProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(botaoClienteAdicionarLayout.createSequentialGroup()
                                        .addComponent(botaoProcurarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoAdicionarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(textoEquipamento)
                            .addComponent(textoModelo)
                            .addComponent(textoNumeroSerie)
                            .addComponent(comboAtendimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(botaoClienteAdicionarLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        botaoClienteAdicionarLayout.setVerticalGroup(
            botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoClienteAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAdicionarCliente)
                    .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoProcurarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(textoTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoProcurarTecnico)
                    .addComponent(botaoAdicionarTecnico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(comboAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(botaoClienteAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textoNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ordem de Serviço", botaoClienteAdicionar);

        botaoAdicionarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/input-mouse-2_menor_add.png"))); // NOI18N
        botaoAdicionarPeca.setText("Adicionar Peça");

        botaoRemoverPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/input-mouse-2_menor_remove.png"))); // NOI18N
        botaoRemoverPeca.setText("Remover Peça");

        tabelaPecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Codigo", "Peça", "Valor", "Quantidade", "Desconto", "Total"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaPecas);

        javax.swing.GroupLayout painelPeçasLayout = new javax.swing.GroupLayout(painelPeças);
        painelPeças.setLayout(painelPeçasLayout);
        painelPeçasLayout.setHorizontalGroup(
            painelPeçasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPeçasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPeçasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(painelPeçasLayout.createSequentialGroup()
                        .addComponent(botaoAdicionarPeca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemoverPeca)))
                .addContainerGap())
        );
        painelPeçasLayout.setVerticalGroup(
            painelPeçasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPeçasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPeçasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionarPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemoverPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Peças", painelPeças);

        tabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Codigo", "Serviço", "Valor", "Desconto", "Total"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelaServicos);

        botaoAdicionarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/chardevice_add.png"))); // NOI18N
        botaoAdicionarServico.setText("Adicionar Serviço");

        botaoRemoverServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/chardevice_delete.png"))); // NOI18N
        botaoRemoverServico.setText("Remover Serviço");

        javax.swing.GroupLayout painelServicosLayout = new javax.swing.GroupLayout(painelServicos);
        painelServicos.setLayout(painelServicosLayout);
        painelServicosLayout.setHorizontalGroup(
            painelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(painelServicosLayout.createSequentialGroup()
                        .addComponent(botaoAdicionarServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemoverServico)))
                .addContainerGap())
        );
        painelServicosLayout.setVerticalGroup(
            painelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemoverServico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Serviços", painelServicos);

        botaoAdicionarPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/money-add.png"))); // NOI18N
        botaoAdicionarPagamento.setText("Adicionar Pagamento");

        tabelaServicos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Vencimento", "Valor", "Pago", "Data Pagamento", "Valor Pago", "Forma Pagamento", "Observação"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabelaServicos1);

        botaoRemoverPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/money-delete.png"))); // NOI18N
        botaoRemoverPagamento.setText("Remover Pagamento");

        jLabel9.setText("Parcelas");

        javax.swing.GroupLayout PainelPagamentosLayout = new javax.swing.GroupLayout(PainelPagamentos);
        PainelPagamentos.setLayout(PainelPagamentosLayout);
        PainelPagamentosLayout.setHorizontalGroup(
            PainelPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPagamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addGroup(PainelPagamentosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAdicionarPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemoverPagamento)))
                .addContainerGap())
        );
        PainelPagamentosLayout.setVerticalGroup(
            PainelPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPagamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPagamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAdicionarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemoverPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(textoParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pagamentos", PainelPagamentos);

        textoObservacoes.setColumns(20);
        textoObservacoes.setLineWrap(true);
        textoObservacoes.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textoObservacoes);

        javax.swing.GroupLayout painelObservacoesLayout = new javax.swing.GroupLayout(painelObservacoes);
        painelObservacoes.setLayout(painelObservacoesLayout);
        painelObservacoesLayout.setHorizontalGroup(
            painelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelObservacoesLayout.setVerticalGroup(
            painelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Observações", painelObservacoes);

        PainelRecebimentos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Recebimentos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jLabel10.setText("Valor Total");

        jLabel11.setText("Valor Pago");

        jLabel12.setText("Valor a Receber");

        jLabel13.setText("Desconto");

        jLabel14.setText("Porcentagem Desconto");

        TextoPorcentagemDesconto.setEditable(false);
        TextoPorcentagemDesconto.setFocusable(false);

        textoDesconto.setEditable(false);
        textoDesconto.setFocusable(false);

        textoTotal.setEditable(false);
        textoTotal.setFocusable(false);

        textoValorPago.setEditable(false);
        textoValorPago.setFocusable(false);

        textoValorReceber.setEditable(false);
        textoValorReceber.setFocusable(false);

        javax.swing.GroupLayout PainelRecebimentosLayout = new javax.swing.GroupLayout(PainelRecebimentos);
        PainelRecebimentos.setLayout(PainelRecebimentosLayout);
        PainelRecebimentosLayout.setHorizontalGroup(
            PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRecebimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoPorcentagemDesconto)
                    .addComponent(textoDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(textoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoValorPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoValorReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelRecebimentosLayout.setVerticalGroup(
            PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelRecebimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(textoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(textoDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TextoPorcentagemDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(textoValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelRecebimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(textoValorReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/accept.png"))); // NOI18N
        botaoSalvar.setText("Salvar");

        botaoProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/magnifier.png"))); // NOI18N
        botaoProcurar.setText("Procurar");

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/pencil.png"))); // NOI18N
        botaoEditar.setText("Editar");

        botaoApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-delete-2.png"))); // NOI18N
        botaoApagar.setText("Apagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(PainelRecebimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelRecebimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoAdicionarClienteActionPerformed
    {//GEN-HEADEREND:event_botaoAdicionarClienteActionPerformed
		CadastroClientes cc = new CadastroClientes();
		cc.setVisible(true);
    }//GEN-LAST:event_botaoAdicionarClienteActionPerformed

    private void botaoAdicionarTecnicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoAdicionarTecnicoActionPerformed
    {//GEN-HEADEREND:event_botaoAdicionarTecnicoActionPerformed
		CadastroUsuario cu = new CadastroUsuario();
		cu.setVisible(true);
    }//GEN-LAST:event_botaoAdicionarTecnicoActionPerformed

    private void botaoProcurarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarClienteActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarClienteActionPerformed
		ProcuraClientes pc = new ProcuraClientes(this, true);
		pc.setVisible(true);
    }//GEN-LAST:event_botaoProcurarClienteActionPerformed

    private void botaoProcurarTecnicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarTecnicoActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarTecnicoActionPerformed
		
    }//GEN-LAST:event_botaoProcurarTecnicoActionPerformed


    /*
     * Métodos da Classe
     */
    
    //METODOS KEYLISTENER
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  

    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {

        }

        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            this.Fechar();
        }
    }
    
    
    /*
     * Método Fechar()
     * Fecha Janela
     */
    private void Fechar()
    {
        this.dispose();
    }
	
	/*
	 * Método getAtendimentos
	 * Obtem todos os atendimentos cadastrados e insere no combobox
	 */
	private void getAtendimentos()
	{
		List<String> atendimentos = new ControladorAtendimentos().getAtendimentos();
		this.comboAtendimento.addItem("");
		for(String atendimento : atendimentos)
			this.comboAtendimento.addItem(atendimento.toString());
	}
	
	/*
	 * Método getClienteByCodigo
	 * Obtem o cliente pelo Codigo
	 */
	public void getClienteByCodigo(Long codigo)
	{
		this.cliente	= new ControladorClientes().getClientesByCodigo(codigo, this);
		this.textoCliente.setText(this.cliente.getNome());
	}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdemDeServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdemDeServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCodigo;
    private javax.swing.JPanel PainelPagamentos;
    private javax.swing.JPanel PainelRecebimentos;
    private javax.swing.JTextField TextoPorcentagemDesconto;
    private javax.swing.JButton botaoAdicionarCliente;
    private javax.swing.JButton botaoAdicionarPagamento;
    private javax.swing.JButton botaoAdicionarPeca;
    private javax.swing.JButton botaoAdicionarServico;
    private javax.swing.JButton botaoAdicionarTecnico;
    private javax.swing.JButton botaoApagar;
    private javax.swing.JPanel botaoClienteAdicionar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JButton botaoProcurarCliente;
    private javax.swing.JButton botaoProcurarTecnico;
    private javax.swing.JButton botaoRemoverPagamento;
    private javax.swing.JButton botaoRemoverPeca;
    private javax.swing.JButton botaoRemoverServico;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox comboAtendimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelObservacoes;
    private javax.swing.JPanel painelPeças;
    private javax.swing.JPanel painelServicos;
    private javax.swing.JTable tabelaPecas;
    private javax.swing.JTable tabelaServicos;
    private javax.swing.JTable tabelaServicos1;
    private javax.swing.JTextField textoCliente;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextArea textoDefeito;
    private formattedFields.jTextMoeda textoDesconto;
    private javax.swing.JTextField textoEquipamento;
    private javax.swing.JTextField textoModelo;
    private javax.swing.JTextField textoNumeroSerie;
    private javax.swing.JTextArea textoObservacoes;
    private javax.swing.JTextField textoParcelas;
    private javax.swing.JTextField textoStatus;
    private javax.swing.JTextField textoTecnico;
    private formattedFields.jTextMoeda textoTotal;
    private formattedFields.jTextMoeda textoValorPago;
    private formattedFields.jTextMoeda textoValorReceber;
    // End of variables declaration//GEN-END:variables
	private OrdemServico	os;
	private Clientes		cliente;
	private Usuario		tecnico;
}
