/*
 * Principal.java
 * 
 * Copyright © 2014 Rogério Eduardo Pereira <rogeriopereira.info@gmail.com>. 
 * 
 * This file is part of AssistenciaTecnica.
 * 
 * AssistenciaTecnica is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AssistenciaTecnica is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AssistenciaTecnica.  If not, see <http ://www.gnu.org/licenses/>.
 */

package assistenciatecnica.view;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import lookandfeel.LookAndFeelWindow;

/**
 *
 * @author Rogério Eduardo Pereira
 * Data Criação: Jun 14, 2014
 */
public class Principal extends javax.swing.JFrame implements KeyListener, ContainerListener
{

	/** Creates new form Principal */
	public Principal() 
	{
		initComponents();

		//Adiciona Listeners de Botões
		addKeyAndContainerListenerRecursively(this);

		this.setLocationRelativeTo(null);

		//Seta Logotipo
		setLogotipo();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu2 = new javax.swing.JMenu();
        painelBotões = new javax.swing.JPanel();
        botaoClientes = new javax.swing.JButton();
        botaoPecas = new javax.swing.JButton();
        botaoOS = new javax.swing.JButton();
        botaoRecibo = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        painelLogotipo = new javax.swing.JPanel();
        labelLogotipo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadastroClientes = new javax.swing.JMenuItem();
        MenuCadastroFornecedores = new javax.swing.JMenuItem();
        MenuMovimentacao = new javax.swing.JMenu();
        MenuMovimentacaoOS = new javax.swing.JMenuItem();
        MenuUtilitarios = new javax.swing.JMenu();
        MenuUtilitariosRecibos = new javax.swing.JMenuItem();
        MenuUtilitariosBackup = new javax.swing.JMenu();
        ManuUtilitariosBackupFazer = new javax.swing.JMenuItem();
        MenuUtilitariosRestaurar = new javax.swing.JMenuItem();
        MenuEmpresa = new javax.swing.JMenu();
        MenuEmpresaDadosEmpresa = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuEmpresaUsuarios = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuEmpresaServicos = new javax.swing.JMenuItem();
        MenuEmpresaPecas = new javax.swing.JMenuItem();
        MenuEmpresaAtendimentos = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        MenuSobreAparencia = new javax.swing.JMenuItem();
        MenuSobreSobre = new javax.swing.JMenuItem();
        MenuSobreLicenca = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assistencia Técnica");
        setPreferredSize(new java.awt.Dimension(800, 600));

        painelBotões.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelBotões.setPreferredSize(new java.awt.Dimension(762, 32));

        botaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-green.png"))); // NOI18N
        botaoClientes.setText("Clientes");
        botaoClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoClientes.setMargin(null);
        botaoClientes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoClientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoClientesActionPerformed(evt);
            }
        });

        botaoPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/input-mouse-2.png"))); // NOI18N
        botaoPecas.setText("Peças");
        botaoPecas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoPecas.setMaximumSize(new java.awt.Dimension(71, 59));
        botaoPecas.setMinimumSize(new java.awt.Dimension(71, 59));
        botaoPecas.setPreferredSize(new java.awt.Dimension(71, 59));
        botaoPecas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoPecas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoPecas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoPecasActionPerformed(evt);
            }
        });

        botaoOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/computer-2.png"))); // NOI18N
        botaoOS.setText("Ordem de Serviço");
        botaoOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoOS.setPreferredSize(new java.awt.Dimension(71, 23));
        botaoOS.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoOS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoOSActionPerformed(evt);
            }
        });

        botaoRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/gnome-sticky-notes-applet.png"))); // NOI18N
        botaoRecibo.setText("Recibo");
        botaoRecibo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoRecibo.setMaximumSize(new java.awt.Dimension(71, 59));
        botaoRecibo.setMinimumSize(new java.awt.Dimension(71, 59));
        botaoRecibo.setPreferredSize(new java.awt.Dimension(71, 59));
        botaoRecibo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoRecibo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/system-shutdown-6.png"))); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSair.setMaximumSize(new java.awt.Dimension(71, 59));
        botaoSair.setMinimumSize(new java.awt.Dimension(71, 59));
        botaoSair.setPreferredSize(new java.awt.Dimension(71, 59));
        botaoSair.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botaoSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoSair.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotõesLayout = new javax.swing.GroupLayout(painelBotões);
        painelBotões.setLayout(painelBotõesLayout);
        painelBotõesLayout.setHorizontalGroup(
            painelBotõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotõesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoOS, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        painelBotõesLayout.setVerticalGroup(
            painelBotõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotõesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoClientes)
                    .addGroup(painelBotõesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botaoSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(botaoOS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRecibo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoPecas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        painelLogotipo.setLayout(new java.awt.BorderLayout());
        painelLogotipo.add(labelLogotipo, java.awt.BorderLayout.CENTER);

        MenuCadastro.setText("Cadastro");

        MenuCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-green_menor.png"))); // NOI18N
        MenuCadastroClientes.setText("Clientes");
        MenuCadastroClientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuCadastroClientesActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroClientes);

        MenuCadastroFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user_menor.png"))); // NOI18N
        MenuCadastroFornecedores.setText("Fornecedores");
        MenuCadastroFornecedores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuCadastroFornecedoresActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadastroFornecedores);

        jMenuBar1.add(MenuCadastro);

        MenuMovimentacao.setText("Movimentação");

        MenuMovimentacaoOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/computer.png"))); // NOI18N
        MenuMovimentacaoOS.setText("Ordem de Serviço");
        MenuMovimentacaoOS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuMovimentacaoOSActionPerformed(evt);
            }
        });
        MenuMovimentacao.add(MenuMovimentacaoOS);

        jMenuBar1.add(MenuMovimentacao);

        MenuUtilitarios.setText("Utilitários");

        MenuUtilitariosRecibos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/gnome-sticky-notes-applet_menor.png"))); // NOI18N
        MenuUtilitariosRecibos.setText("Recibos");
        MenuUtilitariosRecibos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuUtilitariosRecibosActionPerformed(evt);
            }
        });
        MenuUtilitarios.add(MenuUtilitariosRecibos);

        MenuUtilitariosBackup.setText("Backup");

        ManuUtilitariosBackupFazer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/database-save.png"))); // NOI18N
        ManuUtilitariosBackupFazer.setText("Fazer");
        ManuUtilitariosBackupFazer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ManuUtilitariosBackupFazerActionPerformed(evt);
            }
        });
        MenuUtilitariosBackup.add(ManuUtilitariosBackupFazer);

        MenuUtilitariosRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/database-refresh.png"))); // NOI18N
        MenuUtilitariosRestaurar.setText("Restaurar");
        MenuUtilitariosRestaurar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuUtilitariosRestaurarActionPerformed(evt);
            }
        });
        MenuUtilitariosBackup.add(MenuUtilitariosRestaurar);

        MenuUtilitarios.add(MenuUtilitariosBackup);

        jMenuBar1.add(MenuUtilitarios);

        MenuEmpresa.setText("Empresa");

        MenuEmpresaDadosEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/go-home-8.png"))); // NOI18N
        MenuEmpresaDadosEmpresa.setText("Dados da Empresa");
        MenuEmpresaDadosEmpresa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuEmpresaDadosEmpresaActionPerformed(evt);
            }
        });
        MenuEmpresa.add(MenuEmpresaDadosEmpresa);
        MenuEmpresa.add(jSeparator1);

        MenuEmpresaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-black_menor.png"))); // NOI18N
        MenuEmpresaUsuarios.setText("Usuários");
        MenuEmpresaUsuarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuEmpresaUsuariosActionPerformed(evt);
            }
        });
        MenuEmpresa.add(MenuEmpresaUsuarios);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/asterisk-orange.png"))); // NOI18N
        jMenuItem1.setText("Alterar Senha");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuEmpresa.add(jMenuItem1);
        MenuEmpresa.add(jSeparator2);

        MenuEmpresaServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/chardevice.png"))); // NOI18N
        MenuEmpresaServicos.setText("Serviços");
        MenuEmpresaServicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuEmpresaServicosActionPerformed(evt);
            }
        });
        MenuEmpresa.add(MenuEmpresaServicos);

        MenuEmpresaPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/input-mouse-2_menor.png"))); // NOI18N
        MenuEmpresaPecas.setText("Peças");
        MenuEmpresaPecas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuEmpresaPecasActionPerformed(evt);
            }
        });
        MenuEmpresa.add(MenuEmpresaPecas);

        MenuEmpresaAtendimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/network-idle-2.png"))); // NOI18N
        MenuEmpresaAtendimentos.setText("Atendimentos");
        MenuEmpresaAtendimentos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuEmpresaAtendimentosActionPerformed(evt);
            }
        });
        MenuEmpresa.add(MenuEmpresaAtendimentos);

        jMenuBar1.add(MenuEmpresa);

        MenuSobre.setText("Sobre");

        MenuSobreAparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/palette-paint-brush.png"))); // NOI18N
        MenuSobreAparencia.setText("Aparencia");
        MenuSobreAparencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuSobreAparenciaActionPerformed(evt);
            }
        });
        MenuSobre.add(MenuSobreAparencia);

        MenuSobreSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/information.png"))); // NOI18N
        MenuSobreSobre.setText("Sobre");
        MenuSobreSobre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuSobreSobreActionPerformed(evt);
            }
        });
        MenuSobre.add(MenuSobreSobre);

        MenuSobreLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/script.png"))); // NOI18N
        MenuSobreLicenca.setText("Licença");
        MenuSobreLicenca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MenuSobreLicencaActionPerformed(evt);
            }
        });
        MenuSobre.add(MenuSobreLicenca);

        jMenuBar1.add(MenuSobre);

        MenuSair.setText("Sistema");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/system-shutdown-6_menor.png"))); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuSair.add(jMenuItem2);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelBotões, javax.swing.GroupLayout.PREFERRED_SIZE, 766, Short.MAX_VALUE)
            .addComponent(painelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(painelBotões, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(painelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroClientesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuCadastroClientesActionPerformed
    {//GEN-HEADEREND:event_MenuCadastroClientesActionPerformed
		CadastroClientes cadastroClientes = new CadastroClientes();
		cadastroClientes.setVisible(true);
    }//GEN-LAST:event_MenuCadastroClientesActionPerformed

    private void MenuCadastroFornecedoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuCadastroFornecedoresActionPerformed
    {//GEN-HEADEREND:event_MenuCadastroFornecedoresActionPerformed
		CadastroFornecedores cadastroFornecedores = new CadastroFornecedores();
		cadastroFornecedores.setVisible(true);
    }//GEN-LAST:event_MenuCadastroFornecedoresActionPerformed

    private void MenuSobreAparenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuSobreAparenciaActionPerformed
    {//GEN-HEADEREND:event_MenuSobreAparenciaActionPerformed
		lookandfeel.LookAndFeelWindow lookAndFeelWindow = new LookAndFeelWindow();
		lookAndFeelWindow.setVisible(true);
    }//GEN-LAST:event_MenuSobreAparenciaActionPerformed

    private void MenuSobreLicencaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuSobreLicencaActionPerformed
    {//GEN-HEADEREND:event_MenuSobreLicencaActionPerformed
		Licenca licenca = new Licenca();
		licenca.setVisible(true);
    }//GEN-LAST:event_MenuSobreLicencaActionPerformed

    private void MenuEmpresaDadosEmpresaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuEmpresaDadosEmpresaActionPerformed
    {//GEN-HEADEREND:event_MenuEmpresaDadosEmpresaActionPerformed
		DadosEmpresa dadosEmpresa = new DadosEmpresa();
		dadosEmpresa.setVisible(true);
    }//GEN-LAST:event_MenuEmpresaDadosEmpresaActionPerformed

    private void MenuEmpresaUsuariosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuEmpresaUsuariosActionPerformed
    {//GEN-HEADEREND:event_MenuEmpresaUsuariosActionPerformed
		CadastroUsuario cadastroUsuario = new CadastroUsuario();
		cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_MenuEmpresaUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
		AlteraSenha alteraSenha = new AlteraSenha();
		alteraSenha.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ManuUtilitariosBackupFazerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManuUtilitariosBackupFazerActionPerformed
    {//GEN-HEADEREND:event_ManuUtilitariosBackupFazerActionPerformed
		Backup backup = new Backup();
		backup.setVisible(true);
    }//GEN-LAST:event_ManuUtilitariosBackupFazerActionPerformed

    private void MenuUtilitariosRestaurarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuUtilitariosRestaurarActionPerformed
    {//GEN-HEADEREND:event_MenuUtilitariosRestaurarActionPerformed
		RestaurarBackup restaurarBackup = new RestaurarBackup();
		restaurarBackup.setVisible(true);
    }//GEN-LAST:event_MenuUtilitariosRestaurarActionPerformed

    private void botaoClientesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoClientesActionPerformed
    {//GEN-HEADEREND:event_botaoClientesActionPerformed
		CadastroClientes cadastroClientes = new CadastroClientes();
		cadastroClientes.setVisible(true);
    }//GEN-LAST:event_botaoClientesActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoSairActionPerformed
    {//GEN-HEADEREND:event_botaoSairActionPerformed
		this.Fechar();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void MenuSobreSobreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuSobreSobreActionPerformed
    {//GEN-HEADEREND:event_MenuSobreSobreActionPerformed
		Sobre sobre = new Sobre();
		sobre.setVisible(true);
    }//GEN-LAST:event_MenuSobreSobreActionPerformed

    private void MenuUtilitariosRecibosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuUtilitariosRecibosActionPerformed
    {//GEN-HEADEREND:event_MenuUtilitariosRecibosActionPerformed
		Recibos recibos = new Recibos();
		recibos.setVisible(true);
    }//GEN-LAST:event_MenuUtilitariosRecibosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
		this.Fechar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuEmpresaAtendimentosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuEmpresaAtendimentosActionPerformed
    {//GEN-HEADEREND:event_MenuEmpresaAtendimentosActionPerformed
		CadastroAtendimentos cadastroAtendimentos = new CadastroAtendimentos();
		cadastroAtendimentos.setVisible(true);
    }//GEN-LAST:event_MenuEmpresaAtendimentosActionPerformed

    private void MenuEmpresaServicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuEmpresaServicosActionPerformed
    {//GEN-HEADEREND:event_MenuEmpresaServicosActionPerformed
		CadastroServicos cadastroServicos = new CadastroServicos();
		cadastroServicos.setVisible(true);
    }//GEN-LAST:event_MenuEmpresaServicosActionPerformed

    private void MenuEmpresaPecasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuEmpresaPecasActionPerformed
    {//GEN-HEADEREND:event_MenuEmpresaPecasActionPerformed
		CadastroPecas cp = new CadastroPecas();
		cp.setVisible(true);
    }//GEN-LAST:event_MenuEmpresaPecasActionPerformed

    private void MenuMovimentacaoOSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MenuMovimentacaoOSActionPerformed
    {//GEN-HEADEREND:event_MenuMovimentacaoOSActionPerformed
		OrdemDeServico os = new OrdemDeServico();
		os.setVisible(true);
    }//GEN-LAST:event_MenuMovimentacaoOSActionPerformed

    private void botaoPecasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoPecasActionPerformed
    {//GEN-HEADEREND:event_botaoPecasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPecasActionPerformed

    private void botaoOSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoOSActionPerformed
    {//GEN-HEADEREND:event_botaoOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoOSActionPerformed


    /*
     * Métodos da Classe
     */
    
    //METODOS KEYLISTENER
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  

    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {

        }

        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            this.Fechar();
        }
    }
    
    
    /*
     * Método Fechar()
     * Fecha Janela
     */
    private void Fechar()
    {
		System.exit(0);
    }
	
	/*
	 * Método setLogotipo
	 * Define o Logotipo
	 */
	private void setLogotipo()
	{
		this.labelLogotipo.setHorizontalAlignment(SwingConstants.CENTER);  
		this.labelLogotipo.setIcon(new ImageIcon("img\\logotipo.jpg"));
	}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ManuUtilitariosBackupFazer;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuCadastroClientes;
    private javax.swing.JMenuItem MenuCadastroFornecedores;
    private javax.swing.JMenu MenuEmpresa;
    private javax.swing.JMenuItem MenuEmpresaAtendimentos;
    private javax.swing.JMenuItem MenuEmpresaDadosEmpresa;
    private javax.swing.JMenuItem MenuEmpresaPecas;
    private javax.swing.JMenuItem MenuEmpresaServicos;
    private javax.swing.JMenuItem MenuEmpresaUsuarios;
    private javax.swing.JMenu MenuMovimentacao;
    private javax.swing.JMenuItem MenuMovimentacaoOS;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JMenuItem MenuSobreAparencia;
    private javax.swing.JMenuItem MenuSobreLicenca;
    private javax.swing.JMenuItem MenuSobreSobre;
    private javax.swing.JMenu MenuUtilitarios;
    private javax.swing.JMenu MenuUtilitariosBackup;
    private javax.swing.JMenuItem MenuUtilitariosRecibos;
    private javax.swing.JMenuItem MenuUtilitariosRestaurar;
    private javax.swing.JButton botaoClientes;
    private javax.swing.JButton botaoOS;
    private javax.swing.JButton botaoPecas;
    private javax.swing.JButton botaoRecibo;
    private javax.swing.JButton botaoSair;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel labelLogotipo;
    private javax.swing.JPanel painelBotões;
    private javax.swing.JPanel painelLogotipo;
    // End of variables declaration//GEN-END:variables

}
