/*
 * Sobre.java
 * 
 * Copyright © 2014 Rogério Eduardo Pereira <rogeriopereira.info@gmail.com>. 
 * 
 * This file is part of AssistenciaTecnica.
 * 
 * AssistenciaTecnica is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * AssistenciaTecnica is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with AssistenciaTecnica.  If not, see <http ://www.gnu.org/licenses/>.
 */

package assistenciatecnica.view;

import assistenciatecnica.control.ControladorClientes;
import assistenciatecnica.control.ControladorEmpresa;
import assistenciatecnica.control.util.Extenso;
import assistenciatecnica.model.Clientes;
import assistenciatecnica.model.Empresa;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

/**
 *
 * @author Rogério Eduardo Pereira
 * Data Criação: Jun 17, 2014
 */
public class Recibos extends javax.swing.JFrame implements KeyListener, ContainerListener{

    /**
     * Creates new form cadastroMarcas
     */
    public Recibos() {
        initComponents();
        addKeyAndContainerListenerRecursively(this);
        this.setLocationRelativeTo(null);
		this.setEmpresa();
		this.setData();
    }
    
    //BOTAO ESC E ENTER
    //LISTENERS DO FRAME
    //KEYLISTENER RECURSIVO (COLOCA EM TODOS OS COMPONENTES)
    private void addKeyAndContainerListenerRecursively(Component c) 
    {  
        try 
        {  
            c.addKeyListener(this);  
            if (c instanceof Container) 
            {  
                Container cont = (Container) c;  
                cont.addContainerListener(this);  
                Component[] children = cont.getComponents();  
                for (int i = 0; i < children.length; i++) 
                {  
                    addKeyAndContainerListenerRecursively(children[i]);  
                }  
            }  
        } catch (Exception e) {  
            //Anuncie Aqui  
        }  
    }  
    
    //EVENTOS KEYLISTENER
    public void keyTyped(KeyEvent e) {}  
    public void keyReleased(KeyEvent e) {}  
    public void componentAdded(ContainerEvent e) {}  
    public void componentRemoved(ContainerEvent e) {}  
    public void keyPressed(KeyEvent e) 
    {
        //TECLA ENTER
        if(e.getKeyCode() == KeyEvent.VK_ENTER)
        {
            
        }
        
        //TECLA ESC
        if(e.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            dispose();
        }
    }

	/*
	 * MÃ©todo getEmpresa
	 * Obtem os dados da empresa
	 */
	private void setEmpresa()
	{
		this.controlEmpresa = new ControladorEmpresa();
		this.empresa		= this.controlEmpresa.getEmpresa();
		this.textoMunicipio.setText(this.empresa.getCidade());
		this.textoNomeAssinatura.setText(this.empresa.getNome());
		this.controlEmpresa = null;
	}
	
	/*
	 * MÃ©todo setData
	 * Define a data atual do sistema
	 */
	private void setData()
	{
		this.textoData.setCalendar(new GregorianCalendar());
	}
	
	/*
	 * MÃ©todo setClienteByCod
	 * Seta o cliente pelo Codigo
	 */
	public void setClienteByCod(Long codigo)
	{
		this.controlCliente	= new ControladorClientes();
		this.cliente		= this.controlCliente.getClientesByCodigo(codigo, this);
		this.textoCliente.setText(this.cliente.getNome());
		this.controlCliente = null;
	}
	
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        labelRecebemos = new javax.swing.JLabel();
        textoCliente = new javax.swing.JTextField();
        labelImportancia = new javax.swing.JLabel();
        labelReferente = new javax.swing.JLabel();
        painelReferente = new javax.swing.JScrollPane();
        textoReferente = new javax.swing.JTextArea();
        labelObservacao = new javax.swing.JLabel();
        painelObs = new javax.swing.JScrollPane();
        textoObs = new javax.swing.JTextArea();
        labelMunicipio = new javax.swing.JLabel();
        textoMunicipio = new javax.swing.JTextField();
        labelData = new javax.swing.JLabel();
        textoData = new com.toedter.calendar.JDateChooser();
        labelNomeAssinatura = new javax.swing.JLabel();
        textoNomeAssinatura = new javax.swing.JTextField();
        labelComplemento = new javax.swing.JLabel();
        textoComplemento = new javax.swing.JTextField();
        textoValor = new formattedFields.jTextMoeda();
        botaoProcurarCliente = new javax.swing.JButton();
        botaoGerarRecibo = new javax.swing.JButton();
        botaoLimparRecibo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerador de Recibo");
        setBounds(new java.awt.Rectangle(250, 230, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(95, 133, 169), null), "Dados do Recibo"));

        labelRecebemos.setText("Recebemos de:");

        textoCliente.setEditable(false);
        textoCliente.setFocusable(false);

        labelImportancia.setText("A Importância de: ");

        labelReferente.setText("Referente à:");

        textoReferente.setColumns(20);
        textoReferente.setRows(5);
        painelReferente.setViewportView(textoReferente);

        labelObservacao.setText("Observações:");

        textoObs.setColumns(20);
        textoObs.setRows(5);
        painelObs.setViewportView(textoObs);

        labelMunicipio.setText("Municipio");

        textoMunicipio.setEditable(false);
        textoMunicipio.setFocusable(false);

        labelData.setText("Data");

        textoData.setFocusable(false);

        labelNomeAssinatura.setText("Nome (Assinatura)");

        textoNomeAssinatura.setEditable(false);
        textoNomeAssinatura.setFocusable(false);

        labelComplemento.setText("Complemento");

        botaoProcurarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/edit-user-green_menor_buscar.png"))); // NOI18N
        botaoProcurarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoProcurarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomeAssinatura)
                    .addComponent(labelMunicipio)
                    .addComponent(labelData)
                    .addComponent(labelComplemento)
                    .addComponent(labelImportancia)
                    .addComponent(labelRecebemos)
                    .addComponent(labelReferente)
                    .addComponent(labelObservacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(painelReferente, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoMunicipio)
                            .addComponent(textoNomeAssinatura)
                            .addComponent(painelObs, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRecebemos)
                            .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelImportancia)
                            .addComponent(textoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoProcurarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelReferente)
                    .addComponent(painelReferente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelObs, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObservacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNomeAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeAssinatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComplemento)
                    .addComponent(textoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        botaoGerarRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/money-add.png"))); // NOI18N
        botaoGerarRecibo.setText("Gerar Recibo");
        botaoGerarRecibo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoGerarReciboActionPerformed(evt);
            }
        });

        botaoLimparRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assistenciatecnica/view/img/money-delete.png"))); // NOI18N
        botaoLimparRecibo.setText("Limpar Recibo");
        botaoLimparRecibo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                botaoLimparReciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoGerarRecibo)
                        .addGap(18, 18, 18)
                        .addComponent(botaoLimparRecibo)
                        .addGap(133, 133, 133))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGerarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimparRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoGerarReciboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoGerarReciboActionPerformed
    {//GEN-HEADEREND:event_botaoGerarReciboActionPerformed
		SimpleDateFormat	fmtData			= new SimpleDateFormat("dd/MM/yyyy");
							this.extenso	= new Extenso(this.textoValor.getValue());
		String[]			data			= fmtData.format(this.textoData.getDate()).split("/");
		
		if(data[1].equals("01"))
			data[1] = "Janeiro";
		else if(data[1].equals("02"))
			data[1] = "Fevereiro";
		else if(data[1].equals("03"))
			data[1] = "MarÃ§o";
		else if(data[1].equals("04"))
			data[1] = "Abril";
		else if(data[1].equals("05"))
			data[1] = "Maio";
		else if(data[1].equals("06"))
			data[1] = "Junho";
		else if(data[1].equals("07"))
			data[1] = "Julho";
		else if(data[1].equals("08"))
			data[1] = "Agosto";
		else if(data[1].equals("09"))
			data[1] = "Setembro";
		else if(data[1].equals("10"))
			data[1] = "Outubro";
		else if(data[1].equals("11"))
			data[1] = "Novembro";
		else if(data[1].equals("12"))
			data[1] = "Dezembro";
		
		
		System.out.println("Recebemos de: "+textoCliente.getText());
		System.out.println("A importancia de: "+this.extenso.toString());
		System.out.println("Referente Ã : "+this.textoReferente.getText());
		System.out.println(this.textoObs.getText());
		System.out.println("");
		System.out.println	(
								this.textoMunicipio.getText()+", "+
								data[0]+" de "+data[1]+" de "+data[2]
							);
		System.out.println(this.textoNomeAssinatura.getText());
		System.out.println(this.textoComplemento.getText());
    }//GEN-LAST:event_botaoGerarReciboActionPerformed

    private void botaoLimparReciboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoLimparReciboActionPerformed
    {//GEN-HEADEREND:event_botaoLimparReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimparReciboActionPerformed

    private void botaoProcurarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_botaoProcurarClienteActionPerformed
    {//GEN-HEADEREND:event_botaoProcurarClienteActionPerformed
        ProcuraClientes pc = new ProcuraClientes(this, true);
        pc.setVisible(true);
    }//GEN-LAST:event_botaoProcurarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Recibos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoGerarRecibo;
    private javax.swing.JButton botaoLimparRecibo;
    private javax.swing.JButton botaoProcurarCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelImportancia;
    private javax.swing.JLabel labelMunicipio;
    private javax.swing.JLabel labelNomeAssinatura;
    private javax.swing.JLabel labelObservacao;
    private javax.swing.JLabel labelRecebemos;
    private javax.swing.JLabel labelReferente;
    private javax.swing.JScrollPane painelObs;
    private javax.swing.JScrollPane painelReferente;
    private javax.swing.JTextField textoCliente;
    private javax.swing.JTextField textoComplemento;
    private com.toedter.calendar.JDateChooser textoData;
    private javax.swing.JTextField textoMunicipio;
    private javax.swing.JTextField textoNomeAssinatura;
    private javax.swing.JTextArea textoObs;
    private javax.swing.JTextArea textoReferente;
    private formattedFields.jTextMoeda textoValor;
    // End of variables declaration//GEN-END:variables
	private Extenso				extenso;
	private Clientes			cliente;
	private Empresa				empresa;
	private ControladorEmpresa	controlEmpresa;
	private ControladorClientes	controlCliente;
	private ProcuraClientes		janelaProcuraClientes;
}
